<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net9.0</TargetFrameworks>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <EnforceCodeStyleInBuild>True</EnforceCodeStyleInBuild>
    <Platforms>AnyCPU</Platforms>
    <AssemblyName>experiment</AssemblyName>
    <TieredCompilationQuickJit>false</TieredCompilationQuickJit>
    <Trimming>full</Trimming>
    <IncludeAllContentForSelfExtract>true</IncludeAllContentForSelfExtract>
    <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Experiment.CSharp.Library">
      <HintPath>..\Experiment.CSharp.Library\bin\Release\net9.0\Experiment.CSharp.Library.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
