<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFrameworks>net9.0-windows;net8.0-windows</TargetFrameworks>
    <Nullable>enable</Nullable>
    <UseWindowsForms>False</UseWindowsForms>
    <ImplicitUsings>disable</ImplicitUsings>
    <PublishAot>True</PublishAot>
    <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Palmtree.Application\Palmtree.Application.csproj" />
    <ProjectReference Include="..\Palmtree.Core\Palmtree.Core.csproj" />
  </ItemGroup>

</Project>